### ISSUE TITLE
Fix hard reload on new service worker (v 0.x)

### ISSUE THREAD

**Issue by DavidWells** [phenomic/phenomic#1018]
Stop service worker from hard reloading

Instead of `window.location.reload` instantly when service worker is reloaded from a fresh build (https://github.com/MoOx/phenomic/blob/0.21.1/src/_utils/offline/runtime.js#L24) can we change that to reload on the next page load?

```js
onUpdated: () => {
  console.log("SW Event:", "onUpdated")
  const anchors = document.getElementsByTagName("a");
  for (var i = 0; i < anchors.length; i++) {
    anchors[i].onclick = function(e) {
      e.preventDefault()
      // stop react router and just hard reload the clicked href to get new contents
      window.location.href = e.target.href
      return false;
    };
  }
}
```

The code above will loop through all links on the page and disable react-router from doing its thing and instead hard reload the link clicked with the fresh content from the SW.

The `e.preventDefault()` would only happen when the service-worker is changed (aka each build/redeploy)

We have had to turn off the `offline` functionality because our site is rebuilding about 7-10 times a day with updates + new blog posts etc.

Wanted to ping you before I implement/PR

I miss our service worker

ref: https://github.com/MoOx/phenomic/issues/950

**Comment by MoOx** [comment]
Hi @DavidWells!

I totally understand your problem and that sucks. Not sure this solution will make sense for everyone tho. This might depends on what freshness you want for you user. In some case, waiting next page won't make sense.

So good news and bad news:
- 0.x is the past and we won't cut any release for it (due to our limited time)
- Current master branch don't have offline support anymore out of the box (that's the bad news)
- We will offer a mecanism for people to add it back, not sure if we will add an entire SW or a way to allow you to generate it easily using sw-* library (precache or toolbox).

Cause if people want a custom SW, we don't want to block people into our thing.

I hope your understand our situation.

Feel free to throw idea for future offline solution(s).

ETA around 15/20 days for first public alpha (without any SW thing, but should follow).

**Comment by DavidWells** [comment]
@moox we won't be able to port over to v1 immediately 

Can I add this as an option the phenomic object in package.json? For v.0.x only of course

Something like 'disableSWReload': true

By default it will do what it does now unless 'disableSWReload' is defined and then it will do what I need :)

**Comment by DavidWells** [comment]
On a side note, @MoOx your new github profile picture freaks me out 😂

**Comment by MoOx** [comment]
@DavidWells I understand your situation. Feel free to cut a branch from last release and make a PR!

**Comment by MoOx** [comment]
For the avatar, have fun with this: https://twitter.com/MoOx/status/864850663494340608

**Comment by DavidWells** [comment]
Got a PR ready https://github.com/serverless/phenomic/tree/updateSW 

How do we get it published as a `0.21.2` tag? I'm having troubles trying to use this from our fork. 

Looks like our CI/CD (netlify) build can't build phenomic directly from the git repo/branch https://github.com/serverless/site/pull/108/commits/e8680f6e7ca92bf360859ed0e27fbd7e0adb8ca3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R48.

**Comment by MoOx** [comment]
Check out "install from git" section of the "setup" page.

**Comment by MoOx** [comment]
@DavidWells what's the status on this?

**Comment by MoOx** [comment]
There is no SW in v1 for now. Closing with the hope of adding a solid solution in a future release.
