### ISSUE TITLE
Move to an org?

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1023]
We discussed about this multiple time, but the issue is that the name "phenomic" is used on Github.
I reserved "Phenomic-app" but really not happy with this.
I am going to try this:

---

Hi @phenomic, this message is for you and it's not a wrong mention. We are actually a group of people working on a project named "Phenomic", exactly like your github username. The project is currently under my personal username (@MoOx) but we would like to move the repo to an org so here is our question: would you be ready to change your username so we can use it for our org? I am trying since your profile does not seems really active (but I can be totally wrong if you have private repos). I apologies in advance if this message looks inappropriate.

---

Alternatively: do you have a good org name idea?

**Comment by joverdijk** [comment]
Hi,

I don't use Github very much so I don't care giving up the name 'phenomic'

I've changed my accountname into something else already, so probably you are able to use Phenomic for your project now.

Have fun with it ;-)

Best Regards,

The Old Phenomic ;-)



On 17 May 2017, at 12:47, Maxime Thirouin <notifications@github.com<mailto:notifications@github.com>> wrote:


We discussed about this multiple time, but the issue is that the name "phenomic" is used on Github.
I reserved "Phenomic-app" but really not happy with this.
I am going to try this:

________________________________

Hi @phenomic<https://github.com/phenomic>, this message is for you and it's not a wrong mention. We are actually a group of people working on a project named "Phenomic", exactly like your github username. The project is currently under my personal username (@MoOx<https://github.com/moox>) but we would like to move the repo to an org so here is our question: would you be ready to change your username so we can use it for our org? I am trying since your profile does not seems really active (but I can be totally wrong if you have private repos). I apologies in advance if this message looks inappropriate.

________________________________

Alternatively: do you have a good org name idea?

**Comment by MoOx** [comment]
@joverdijk thank you so much!

Here is the new org (will move repo later) http://github.com/phenomic
