### ISSUE TITLE
Problems with v1.0.0-alpha.2 some peerdeps are missing

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1049]
Following packages have to be installed manually:
- webpack
- webpack-dev-middleware
- to be sure react-router@3.0.0 not higher

Then on 2.md it say's: Now we can use npm start to start the website/app. Website/app should be accessible via http://localhost:3333.
This not true, because we miss a `content` folder.

Maybe directly suggest to separate Home function in his own file, because of this message:
- React Hot Loader: `React Hot Loader: Home in /Users/johnripke/Desktop/Developer/Javascript/syndia/site-v1/App.js will not hot reload correctly because App.js uses <Home /> during module definition. For hot reloading to work, move Home into a separate file and import it from App.js.`

If I found more, I will add them ;)

**Comment by themarkappleby** [comment]
Even when fixing the version of react-router to 3.0.0 I am getting `Cannot find module 'react-router/lib/RouteUtils'`.

**Comment by kbariotis** [comment]
Just played with Phenomic following the docs and got onto those exact problems. It was easy to bypass them (by installing missing deps and manually creating the content folder) but for a newcomer may be not that easy. The docs at least should be updated. Other than that all went so smooth. Well done guys, amazing job!

**Comment by thangngoc89** [comment]
@kbariotis The current docs is 1.0-alpha.. At least v0.2x works very well.

**Comment by MoOx** [comment]
Thank you guys for reporting. Indeed some deps are peerDeps so people are not stuck if they want specific version.
That said, I am thinking about adding those deps in the preset. So with the preset, you have everything you need, and if you need some specific stuff, you can just grab preset and tweaks version. What do you think about that?

@themarkappleby weird, this files actually exist, see https://unpkg.com/react-router@3.0.0/lib/RouteUtils (or even https://unpkg.com/react-router@^3.0.0/lib/RouteUtils. Can you reinstall and double check please?

I am filling another issue for "content" folder because that should not be a blocker. Same for public. See https://github.com/phenomic/phenomic/issues/1056 & https://github.com/phenomic/phenomic/issues/1055

For the hot loading warning, I will just add a note, because I would like the getting started to fit in a file.

Feel free to open different issues if you find more bugs/docs inconsitencies, I will keep this one for deps.

**Comment by themarkappleby** [comment]
@MoOx just tried reinstalling the react-router package and that seems to have resolved it, cheers 🍻!
