### ISSUE TITLE
phenomic vs gatsby

### ISSUE THREAD

**Issue by Maxhodges** [phenomic/phenomic#1122]
Can anyone tell me what are the key differences between Gatsby and Phenomic? Last year I tried using Gatsby but that Phenomic has much better docs. But now it seems Gatsby has developed quite a bit and has more to offer then Phenomic. Why don't you guys just work together on one system? Seems like you're basically doing the same thing.
Cheers!

**Comment by MoOx** [comment]
There is plenty of differences and many reasons Gatsby is more famous today but I will just throw some here until I have more time (probably next month).

For now what Gatsby has over Phenomic (comparing v1.x) is offline support as we didn't implement anything yet in 1.0 alpha (but that's coming).

One thing were Phenomic is already more smart is pagination. We think in a way it's a core feature for static content. Gatsby offers nothing and we offer a immutable pagination (more about this in the getting started docs)!

Huge difference as of today: Gatsby rely on React and Webpack. Phenomic does not and can work with other solutions (to be implemented). So for example you can imagine Phenomic+Angular+rollup or anything we can imagine.
We made this choice for performance because webpack is slow and relying on it is not a good idea.
Relying on webpack for a huge scalable website is not a good idea in the first place.
We will soon create some benchmarks and we might get some surprises.

Also Gatsby decided to go full graphql an we think it's not a good idea for simple website as it can create overfetching (since all queries can request redundant content). But that said we may add later a graphql interface for querying content.

We think we are offering a much simpler api. You can just compare some examples (to come): gatsby require more configuration and boilerplate for a simple website.
Again we will create a fair comparision when we reach stable 1.0 (since people will continue to ask this question until Phenomic get as many "stars" as Gatsby)

Also, Gatsby as more to offer today since his core maintainer has found lots of sponsors during the next few months. We don't so development of Phenomic is slower.

We cannot just "work" together as architecture of both projects (and long term goal?) are different. But competition isn't that bad right? 

We think you will heard more about Phenomic in the next couple of month when we reach stable 1.0. ;)

**Comment by Maxhodges** [comment]
hi @MoOx 

Thanks for the perspective. I opened this question, then found the FAQ about Gatsby, so I closed it.

Sure competition is good, but I just thought if the devs could agree on the same aims then you could have one project with twice the resources. Some of us have sites we need to build yesterday, so we need to use whatever tools are available to us--we can't always wait until tomorrow for something better to emerge. But it's just the nature of web dev these days that everything is changing all the time, and it can be extremely difficult to make decisions about tool chains, UI frameworks, etc. because of the churn.

Would you recommend Phenomic over Gatbsy for all use-cases? We need to create some static sites now. We would like to stay in JavaScript, host on Netlify, and pull content from Conentful. We are already using React (in our Meteor projects). We don't expect out site to be so large that Webpack performance would be unacceptable. 

It sounds like Phenomic is trying to be all-things-to-all-people (in it's agnosticism about build tools and UI frameworks). You're worried about leaving Angular users behind, and while you worry that GraphQL might over-fetch, you're thinking you may throw it in anyway (so people have no reason to use another product). That could ultimately help Phenomic reach a large audience, but aren't there high-costs in terms of agility to developing and maintaining all that flexibility and complexity? Maybe Gatsby is moving faster because they're making hard decisions about simplicity vs flexibility?

**Comment by revolunet** [comment]
in all cases, i think you should create your ui components (and even "pages")  separately, out of your "static builder". Create all your react reusable components, then phenomic (or gatsby or whatever) will "just" make the glue between your components and your data.

**Comment by MoOx** [comment]
@Maxhodges I am a bit biased, but I don't think Gatsby have more values that Phenomic when we will reach stable v1.
Gatsby is surely moving faster... For now!
We are probably moving slower, but I guess we should be able to adapt to community changes!

What if webpack stop evolving and a new bundler emerge? Oh I see Metro bundler over there... :)
Gatsby heavily rely on webpack so far and this cause 2 major problem imo: speed and scalability.

**Comment by Maxhodges** [comment]
so many developments in this space!
https://graphcms.com/

**Comment by xuopled** [comment]
Pulling content directly from `Contentful` or `GraphCMS` will be amazing when it could be possible with `Phenomic` 1.0

**Comment by MoOx** [comment]
Will be part of docs
