### ISSUE TITLE
Vue Plugin/preset/example

### ISSUE THREAD

**Issue by ankitrg** [phenomic/phenomic#1145]
I would like to use Phenomic with Vue.js, has there been any effort on this front? Is there a branch or a guide on how someone can go about doing this? I would like to contribute if I can in some way.

**Comment by MoOx** [comment]
No effort has been made yet from what I know.
There is no branch yet and docs for internals are not to be done.
I guess it's a nice moment to think about it.

What need to be done:

- make a plugin-renderer-vue inspired by the react renderer plugin https://github.com/phenomic/phenomic/tree/master/packages/plugin-renderer-react.
You will need to take a look to the format expected by the phenomic core for the routes returned by the plugin.

- make at least an example (used for automated testing since it's most of the time more easy than writing unit test)

I don't know vuejs (yet) but I am very interested to have this for final 1.0.0!

Most up to date branch is the 1.0.0-alpha.6.
I guess I should use master branch instead of this kind of PR but at the same time I am hesitating since it's not helping to quickly view what has been released and what is not.
Maybe a master (stable/released) and a dev branch could do it.

You will need yarn to be able to setup the monorepo. Just clone the repo, cut a branch from 1.0.0-alpha.6 and do `yarn`. It should setup everything needed for you to have the project fully working. You can probably even use `npm test` or `yarn run test` to see all the test executed:

- required transpilation
- unit tests
- examples builded
- docs builded

If you want to play with an example, you can create an example from other, replace the preset in the config by a list of plugins (with your newly created plugin) and play with.

You can use the watcher for transpilation via `npm run watch` or `yarn run watch`.

If you have any questions or comments, you can continue here, and/or use our chat https://gitter.im/MoOx/phenomic

Looking forward to your contribution!

**Comment by MoOx** [comment]
If you need anything, let us know!

**Comment by ankitsinghaniyaz** [comment]
@MoOx I forked the code and I am seeing how the React renderer is implemented. I'll come back to you if I'm in need of something.

**Comment by MoOx** [comment]
I made some minor changes yesterday a-on alpha 6 branch. Code should be a bit more clear (less confusion) maybe :)

**Comment by MoOx** [comment]
I made some minor changes yesterday on alpha 6 branch. Code should be a bit more clear (less confusion) maybe :)

**Comment by ankitsinghaniyaz** [comment]
Sure, I'll check it out.

**Comment by MoOx** [comment]
Do you need any help?

**Comment by marioacc** [comment]
Is there something I could help?

**Comment by sbaidon** [comment]
I would love to help as well if possible! 👍

**Comment by MoOx** [comment]
@ankitsinghaniyaz @ankitrg @marioacc @sbaidon if you want I can all give you write access to the repo so you can work together on a branch. Who is interested?

**Comment by sbaidon** [comment]
I would we up for it, I just need a bit of guidance

**Comment by ankitrg** [comment]
Yes @sbaidon , I agree a little walkthrough would be good enough.

**Comment by marioacc** [comment]
I am interested, but as well I need a walkthrough 😄

**Comment by marioacc** [comment]
@MoOx, Is the proposal still available?

**Comment by MoOx** [comment]
Yeah sure. Feel free to use this issue to discuss about what you need or with our chat http://gitter.im/phenomic/phenomic.
Check out the CONTRIBUTING.md and what https://github.com/phenomic/phenomic/tree/master/packages/plugin-renderer-react is exporting. You can also check https://github.com/phenomic/phenomic/blob/82bca0ad377b515e00ab945ada9d5941dc22af5b/flow/interfaces/phenomic.js#L113-L115

Also be sure to talk to each others to not start working on the same thing. I am adding all of you to the repo!

@ankitsinghaniyaz Did you start something? @ankitrg You have a very similar name to @ankitsinghaniyaz so I am curious, are you the same person?

**Comment by MoOx** [comment]
Btw, if you need some changes to the current API, do not hesitate to discuss about it, we are open!

**Comment by ankitsinghaniyaz** [comment]
@MoOx Yes, they both are my profile I use two profiles for some reason. I'll correspond here with this profile. I haven't got a chance to spend time on the codebase. I looked into the render and how it works, but it seems I have to put in some more effort to understand it better.

**Comment by sicavalentine** [comment]
I have 2+ years experience with both React and Vuejs and can help if needed :D

**Comment by MoOx** [comment]
I am going to write a doc on what phenomic expects, that might help you :)

**Comment by nathanchere** [comment]
Is anyone *actively* working on this before I start on it?

**Comment by MoOx** [comment]
Nobody yet from what I know

**Comment by MoOx** [comment]
@nathanchere tell me if you want to work on this, I can add you as a collab for the repo

**Comment by ankitsinghaniyaz** [comment]
I've some time now and I would like to start again. @MoOx I just had the question will there be two different plugins for Vue and Nuxt? Just like React and Next?

**Comment by MoOx** [comment]
I am not familiar with Nuxt, but if it's hide the "build" part like Next does I guess so.

**Comment by mandaputtra** [comment]
Still open? I would like to help

**Comment by MoOx** [comment]
You can help. It's still open indeed. Note that I am AFK this days that's why project is not moving :) (will probably be back in September)

**Comment by mandaputtra** [comment]
okay, please guide me, I will fork first. Anyone in this project, please contact me to work together

**Comment by medfreeman** [comment]
i'm also interested in this, but for Nuxt.js.
i wonder if vue and nuxt plugins will share code somehow.
btw, i'm in the process of finishing [`remark-vue`](https://github.com/medfreeman/remark-vue), so markdown can be compiled safely to vue (it needs a few contributions to [hast-to-hyperscript](https://github.com/syntax-tree/hast-to-hyperscript) before reaching a stable stage).
I'll also probably transform this to a monorepo (want to try lerna), with a second `rehype-vue` package, in order to be more in-line with what's done in [`@phenomic/helpers-transform`](https://github.com/phenomic/phenomic/blob/a9a23f66260e55df30de46b75b319e9f4f5b57b7/packages/helpers-transform/src/unifiedProcessor.js#L5)

**Comment by mandaputtra** [comment]
@medfreeman interesting, what issue i can help?

**Comment by medfreeman** [comment]
@mandaputtra
concerning remark-vue, i only need to finish writing tests for hast-to-hyperscript, wait for merge and release a new version.
Then publishing rehype-vue, which should basically be the same without a few lines of code doing basically what remark-rehype does.
then figuring / asking how to extend the unified processor to use this module, and removing rehype-react.

concerning a phenomic-nuxt plugin, that would probably be, as for next.js, a combination of a renderer and a bundler plugin, since nuxt takes care of both of these.
@phenomic/plugin-bundler-renderer-nuxt

The first part should be what will be of use to both of the vue and nuxt plugins.
Then, if nuxt inherits some things about routes formats, app tree decoration or smth from vue, we'll probably have to share some code in a helper package.

**Comment by MoOx** [comment]
Not a priority atm. Feel free to discuss below. 
Note that phenomic will somehow gets a new shape and this doesn't mean a Vue plugin won't make sense (so Vue plugin might be something!)
