### ISSUE TITLE
Styled-components example style hot reloadin

### ISSUE THREAD

**Issue by drFabio** [phenomic/phenomic#1179]
Does the styles when using the [styled-components example](https://github.com/phenomic/phenomic/tree/master/examples/react-app-styles-with-styled-components) should be hot reloaded?

It seems that using the hot reload works except when updating styles

**Comment by MoOx** [comment]
It's "on purpose".
There is 2 reasons for that.
- The example is really minimal and does not include the hot module require code https://github.com/phenomic/phenomic/blob/86b7188adc1790bbb5ed4ebe4cdf8a8a1f766b34/examples/react-app-getting-started/App.js#L159-L161
- even if we include it, since everything is in a single file, it will not work (you will get a warning about that anyway).

I guess you know what to do now :) Feel free to continue discussion here if necessary.

**Comment by drFabio** [comment]
Got it. I had the hot reloadding but the same file included was what made it .
Thanks!
