### ISSUE TITLE
Don't throw NotFoundError when accessing a not found entry

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#1222]
Currently, at this line https://github.com/phenomic/phenomic/blob/33258f441b44302841ebe055319741d3ed985581/packages/core/src/db/index.js#L149 , the database will throw NotFoundError and kill the whole server with it. We should handle this case gracefully and send a 404 code back to user.

**Comment by MoOx** [comment]
Don't mix "db" code with "server api" code. Currently we are supposed to handle this with this kind of code https://github.com/phenomic/phenomic/blob/33258f441b44302841ebe055319741d3ed985581/packages/core/src/api/index.js#L153-L156

The error you are facing may be related to the resolver, which access db with direct access (via db api) that's why 404 does not make sense at this stage.

**Comment by thangngoc89** [comment]
Ah. Make senses. What I mean is the console.error. It’s really annoying. And it doesn’t tell me which ID is not found. Will work on this

**Comment by thangngoc89** [comment]
On second thought, I know that throwing when accessing a unknown ID is leveldb behavior but it's a little bit too aggressive. I don't want to have try/catch everywhere. I usually return `null` for this case. This is what others Databases do (MongoDB, MySQL, ...). Any thoughts? 

And I wish we have pattern matching here.

**Comment by MoOx** [comment]
We should probably "just" catch from the resolver and handle this a better way. But in practise it's more a user problem than a real bug.

**Comment by MoOx** [comment]
The situation is better already.
