### ISSUE TITLE
Custom build directory

### ISSUE THREAD

**Issue by natebrunette** [phenomic/phenomic#1227]
Is it possible to build to a custom directory that's not `dist`?

**Comment by MoOx** [comment]
You can use `outdir` option via "phenomic" section in package.json (or via .phenomicrc since we use [cosmicconfig](https://github.com/davidtheclark/cosmiconfig).

See current available options here: https://github.com/phenomic/phenomic/blob/374a090438289efb90308ccaaa08916c3312aff8/packages/core/src/defaultConfig.js

I need to document that.

**Comment by natebrunette** [comment]
Thanks!

**Comment by natebrunette** [comment]
Reopening in case you want to use this issue to track progress on adding the documentation. Close if not.

**Comment by MoOx** [comment]
Will be part of docs
