### ISSUE TITLE
`composes` throw stylelint warning

### ISSUE THREAD

**Issue by asimkt** [phenomic/phenomic#1245]
```
.siteReference {
  /* stylelint-disable */
  composes: phenomicReference;
  /* stylelint-enable */
}
```
Without disabling stylelint a `composes` property of CSS-modules will throw a warning saying: _"	⚠  Unexpected unknown property "composes" (property-no-unknown) [stylelint]"_ 

I think we should change the stylelint config to add `composes` support.

**Comment by MoOx** [comment]
This problem is related to 0.x.
You can probably handle this by yourself by changing your stylelint config, right?

1.x doesn't imposes anything like this (not even stylelint) and all my current effort are spend on releasing this version as stable. I don't want to spend time on this kind of issues (I will only accept bugfixes for 0.x).

Hope you understand the situation.

(Before you ask, 1.0 will provide a migration guide).
