### ISSUE TITLE
Content not loading in browser

### ISSUE THREAD

**Issue by nalanirojas25** [phenomic/phenomic#1272]
Hello,
I'm having trouble loading the page in the 03.md section of the tutorial.
Here is what the browser is loading: 
![browser](https://user-images.githubusercontent.com/33745492/52180297-b320cd00-27a1-11e9-9a11-83640434fdfc.png)

Here is my App.js file setup:
![appjs](https://user-images.githubusercontent.com/33745492/52180317-1448a080-27a2-11e9-8646-875ba803ea16.png)

And here is my package.json file setup: 
![packagejsonimg](https://user-images.githubusercontent.com/33745492/52180324-24608000-27a2-11e9-8612-86d78b120faa.png)
 
Things I've tried: 
I've tried including this object into the package.json:
  "content": {
    "": {
      "root": "content",
      "globs": ["**/*"]
    }

and I've tried changing the pathway to the best of my knowledge. However, I haven't been able to get it to work. Its also not giving any errors so I'm out of ideas on what else I can do to solve this problem. I would greatly appreciate someone's help. 

Thank You.

**Comment by MoOx** [comment]
@nalanirojas25 Can you publish your entire App.js so I can try to run it?

**Comment by nalanirojas25** [comment]
@MoOx https://github.com/nalanirojas25/phenomic-tutorial

**Comment by MoOx** [comment]
It's simple: you `first-post.md`is empty!
If should contains the content specified in the first code block https://phenomic.io/en/packages/preset-react-app/docs/getting-started/03/

See https://raw.githubusercontent.com/phenomic/phenomic/master/examples/react-app-getting-started/content/posts/first-post.md

Not that the part above "# This is a markdown..." is added later in the tutorial.

I have to admit this part is totally unclear, sorry about that.

Unrelated advice
- add a gitignore to a project to avoid commiting node_modules (it costing a lot of space, slow to commit, upload etc). That's why there is a package lock :)

See https://github.com/phenomic/phenomic/blob/f7b9e0c5d0e38dd350856ef90cb8f74f0c4df2c6/.gitignore#L3-L7

**Comment by nalanirojas25** [comment]
Yeah, that was the problem and will do on the .gitignore file, I forgot to include that. Thanks for that!
