### ISSUE TITLE
Updating to newer releases?

### ISSUE THREAD

**Issue by tconroy** [phenomic/phenomic#954]
Hello!

I was hoping you could provide some documentation on how to update a Phenomic based projects to a newer version of Phenmoic.

I have a project based off of v0.19.5 and now want to update to the latest phenomic. I tried merging in phenomic/master, but now I'm not seeing any start command in package.json so I'm assuming that wasn't the correct way to update.

Any guidance would be much appreciated! 👍

**Comment by MoOx** [comment]
The best way to upgrade is to read changelog notes.
You can find those in releases page https://github.com/MoOx/phenomic/releases or in the CHANGELOG file https://github.com/MoOx/phenomic/blob/master/CHANGELOG.md.

You basically need to look for breaking changes (if any) and follow instructions (again, if any). In your case, 0.20.x does not have any breaking changes compared to 0.19 so you can easily upgrade by just changing phenomic version number in your package.json and running "npm install".

Tell me if this instructions are clear enough.

**Comment by tconroy** [comment]
Hi @MoOx -- 

My apologies, I assumed the upgrade process was more complex than that! Bumping the version number is quite simple. However, I'm not sure how to keep things like the webpack config etc. up to date with phenomic -- this just seems to keep the phenomic module itself up to date?

Apologies if I'm misunderstanding. :) 

Thanks!

**Comment by MoOx** [comment]
If anything has to be updated, you will find instructions in the release notes.

Example here https://github.com/MoOx/phenomic/releases/tag/0.17.0 (and there where not a lot of required changes from user side).

**Comment by tconroy** [comment]
Great! So just need to keep an eye on the release notes and make minor adjustments as necessary. Simple enough.

Thanks for the quick response! Cheers. 🍻

**Comment by stephanedaviet** [comment]
I bump this issue because I have a few questions and perhaps proposals. Phenomic has two parts: the library that is easily updatable, and the site structure and tooling that is a bit harder as it involved some manual reconciliation steps based on reading the changelog.

I know that Yeoman provides some scaffolding à la `phenomic setup`. Moreover, some tools based on Yeoman like JHipster provide a migration tooling (https://jhipster.github.io/upgrading-an-application/). 

Perhaps it would be possible to do the same for Phenomic, something like `phenomic update` that would do all the required stuff both for the structure and the library updates.

**Comment by MoOx** [comment]
This is a good idea. codemods is also something I was thinking about. The only problem here is the limited time I have and the fact that there is currently no active contributors...

**Comment by MoOx** [comment]
Will be part of docs
